spring:
    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: belong
        password: belong
        
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
