server:
    port: 15000

spring:
    datasource:
        url: jdbc:h2:mem:PhoneNumberDB
        driverClassName: org.h2.Driver
        username: belong
        password: belong
        
    h2:
        console:
            enabled: true
        
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect