INSERT INTO CUSTOMER (ID,TITLE,NAME,SURNAME) VALUES (1,'Dr','Grape','Avocado');
INSERT INTO CUSTOMER (ID,TITLE,NAME,SURNAME) VALUES (2,'Mr','Apple','Carrot');
INSERT INTO CUSTOMER (ID,TITLE,NAME,SURNAME) VALUES (3,'Mr','Banana','Beans');
INSERT INTO CUSTOMER (ID,TITLE,NAME,SURNAME) VALUES (4,'Mrs','Apricot','Asparagus');
INSERT INTO CUSTOMER (ID,TITLE,NAME,SURNAME) VALUES (5,'Ms','Melon','Aubergine');
INSERT INTO CUSTOMER (ID,TITLE,NAME,SURNAME) VALUES (6,'Mr','Grape','Beetroot');
INSERT INTO CUSTOMER (ID,TITLE,NAME,SURNAME) VALUES (7,'Mr','Nut','bean');
INSERT INTO CUSTOMER (ID,TITLE,NAME,SURNAME) VALUES (8,'Mrs','Olive','Broccoli');
INSERT INTO CUSTOMER (ID,TITLE,NAME,SURNAME) VALUES (9,'Ms','Orange','Olive');
INSERT INTO CUSTOMER (ID,TITLE,NAME,SURNAME) VALUES (10,'Dr','Peanut','Pepper');


INSERT INTO PHONE_NUMBER (ID,NUMBER,CUSTOMER_ID) VALUES (1,0421502121,1);
INSERT INTO PHONE_NUMBER (ID,NUMBER,CUSTOMER_ID) VALUES (2,0433541545,4);
INSERT INTO PHONE_NUMBER (ID,NUMBER,CUSTOMER_ID) VALUES (3,0451515487,3);
INSERT INTO PHONE_NUMBER (ID,NUMBER,CUSTOMER_ID) VALUES (4,0445151548,4);
INSERT INTO PHONE_NUMBER (ID,NUMBER,CUSTOMER_ID) VALUES (5,0455455445,null);
INSERT INTO PHONE_NUMBER (ID,NUMBER,CUSTOMER_ID) VALUES (6,0421451544,5);
INSERT INTO PHONE_NUMBER (ID,NUMBER,CUSTOMER_ID) VALUES (7,0421444545,4);
INSERT INTO PHONE_NUMBER (ID,NUMBER,CUSTOMER_ID) VALUES (8,0421451242,null);
INSERT INTO PHONE_NUMBER (ID,NUMBER,CUSTOMER_ID) VALUES (9,0421454847,6);
INSERT INTO PHONE_NUMBER (ID,NUMBER,CUSTOMER_ID) VALUES (10,0421458889,7);
INSERT INTO PHONE_NUMBER (ID,NUMBER,CUSTOMER_ID) VALUES (11,0421453536,null);
INSERT INTO PHONE_NUMBER (ID,NUMBER,CUSTOMER_ID) VALUES (12,0421454748,6);
INSERT INTO PHONE_NUMBER (ID,NUMBER,CUSTOMER_ID) VALUES (13,0421451454,7);



